### PR TITLE
docs: warp-435 Add Do and Dont boxes for documentation

### PR DESCRIPTION
**Pull request by Skadefryd**
**Useage:**
```
<do-dont>

  <do imgurl="..." imgalt="...">
    YO, dont be dumb, Do this!
  </do>

  <do not imgurl="..." imgalt="...">
    HEY, dont be dumb, Dont do this!
  </dont>

  <do not imgurl="..." imgalt="...">
    HEY, dont be dumb, Dont do this!
  </dont>

</do-dont>
```
image

**Useage, with no image:**
```
<do-dont>

  <do>YO, dont be dumb, Do this!</do>

  <do not>HEY, dont be dumb, Dont do this!</dont>

  <do not>HEY, dont be dumb, Dont do this!</dont>

</do-dont>
```
image

### CODE REVIEW

**Review by BalbinaK — COMMENTED** [review]
Question: is it always going to be the `DoDont` component that will be used? If so, I'm thinking that we could maybe make it the only component and include all styles for both Do and Dont component there. I'm no pro in Vue but I _think_ you could make it accept 4 slots: #do-img, #dont-img, #do and #dont. I've been looking at how we solved it for Vue TextField: [here's how you'd pass multiple slots to TextField](https://github.com/warp-ds/vue/blob/next/dev/pages/TextField.vue#L46-L49). Then in the component you'd have named slots, like so:
```
        <div v-if="$slots.do-img" class="figure"> // I found this resource on how to check if slot is not empty: https://mokkapps.de/vue-tips/check-if-slot-is-empty#check-if-a-slot-is-empty
          <slot name="do-img" class="img"></slot>
        </div>
        <div class="caption">
          <slot name="do"></slot>
        </div>
        ...
        <div v-if="$slots.dont-img" class="figure">
          <slot name="dont-img" class="img"></slot>
        </div>
        <div class="caption">
          <slot name="dont"></slot>
        </div>

**Comment by Skadefryd** [comment]
> make it accept 4 slots: #do-img, #dont-img, #do and #dont.

There can be any number of do's and any number of dont's, would that be feasible with the model you describe? To solve absolutely everything Jon-Olav describes it has to be possible to choose a left/right position pr box in this thing as well  so a more granular setup is needed isnt it?.

**Comment by BalbinaK** [comment]
>> make it accept 4 slots: #do-img, #dont-img, #do and #dont.
>
> There can be any number of do's and any number of dont's, would that be feasible with the model you describe? To solve absolutely everything Jon-Olav describes it has to be possible to choose a left/right position pr box in this thing as well  so a more granular setup is needed isnt it?.  

I have a feeling there is a way to utilize [Vue slots](https://vuejs.org/guide/components/slots.html) to achieve what was described in [WARP-435](https://nmp-jira.atlassian.net/browse/WARP-435), but I don't know if there's some limitations if we want multiple slots of the same name, or to what extent we'd benefit from using named slots at all here. Maybe @magnuh has some instant thoughts whether there's potential in using some more advanced slots in a DoDont component.

**Comment by magnuh** [comment]
I actually think that we could scrap the dodont wrapper? 🤷  It is just a grid, that could be made more dynamic just using styling however you want? 😅 
But I DO think that we should make the do and dont components into one single component, since it is just mostly duplication... and we could then use it as `<do />` and `<do not />`.

**Comment by magnuh** [comment]
Is it always going to be an image in that box? 🤔  Otherwise it might be better to have a named slot for that area?

**Comment by Skadefryd** [comment]
> I actually think that we could scrap the dodont wrapper? 🤷 It is just a grid, that could be made more dynamic just using styling however you want? 😅

Isnt the whole point of this to simplify stuff for the designers as much as possible? Having them deal with the grid every time they have to write docs is not exactly that in my opinion.  My angle of attack for the thing was to set up a absolute minimum simple to understand markup and make that work.  If we ever need any other grid setup for this, we can just drop that grid-wrapper and do whatever with a custom grid for that case, no problem.

**Comment by Skadefryd** [comment]
> Is it always going to be an image in that box? 🤔 Otherwise it might be better to have a named slot for that area?

Nothing other than a image in the image area.  If I understand the sketches correctly.  Was purely images in the previous ds system aswell.

**Comment by magnuh** [comment]
Ah ok, didn't understand that it was the designers that were going to use this themselves. 😅 👍

**Comment by magnuh** [comment]
Added a suggestion with the `Dont` component merged into the `Do` component by adding a `not` prop: https://github.com/warp-ds/tech-docs/pull/180 ...Wdyt? 🙂

**Review by magnuh — APPROVED** [review]

**Pull request merged**
