### PR TITLE
docs: add icons v1.3.0 blog post

### PR DESCRIPTION
**Pull request by siljec**
Adding updates to icons to "What's new" section

image
image

### CODE REVIEW

**Review by BalbinaK — APPROVED** [review]
🎉

**Review by felicia-haggqvist — APPROVED** [review]

**Comment by felicia-haggqvist** [comment]
I get a build error when trying to run `pnpm build`: 
Skärmavbild 2023-11-24 kl  15 18 53

Skärmavbild 2023-11-24 kl  15 15 48

But it looks fine when I run `pnpm dev` and the link to the icons-section of the tech-docs works! 😺

**Comment by siljec** [comment]
Thanks for checking @felicia-haggqvist <3 I was a bit too fast there :p I updated it now

**Review by felicia-haggqvist — APPROVED** [review]

**Review by Skadefryd — APPROVED** [review]
Nice!

**Pull request merged**
