### PR TITLE
feat(forms): add docs for forms

### PR DESCRIPTION
**Pull request by CarolineGard**
This is a quick copy from fabric docs. 
Need to go through this component and test it.

### CODE REVIEW

**Review by BalbinaK — CHANGES_REQUESTED** [review]
It looks like this component was covered in Textfield page, under `vue` tab: https://warp-ds.github.io/tech-docs/components/textfield/

**Comment by CarolineGard** [comment]
> It looks like this component was covered in Textfield page, under `vue` tab: https://warp-ds.github.io/tech-docs/components/textfield/

Nice catch! but hm okay. It's a bit weird it's in `Textfield` as `forms` covers the other forms components as well. But should we keep it there and remove this whole page, what do you think? It's a bit confusing either way I think 😅

**Comment by BalbinaK** [comment]
> > It looks like this component was covered in Textfield page, under `vue` tab: https://warp-ds.github.io/tech-docs/components/textfield/
> 
> Nice catch! but hm okay. It's a bit weird it's in `Textfield` as `forms` covers the other forms components as well. But should we keep it there and remove this whole page, what do you think? It's a bit confusing either way I think 😅

@CarolineGard When I checked the other Form-related Vue components we've moved to Warp, all of them mention Form component and validation. I think it's enough for users and helps us keep the sidebar structure a bit more consistent across frameworks. Wdyt?

**Comment by CarolineGard** [comment]
> > > It looks like this component was covered in Textfield page, under `vue` tab: https://warp-ds.github.io/tech-docs/components/textfield/
> > 
> > 
> > Nice catch! but hm okay. It's a bit weird it's in `Textfield` as `forms` covers the other forms components as well. But should we keep it there and remove this whole page, what do you think? It's a bit confusing either way I think 😅
> 
> @CarolineGard When I checked the other Form-related Vue components we've moved to Warp, all of them mention Form component and validation. I think it's enough for users and helps us keep the sidebar structure a bit more consistent across frameworks. Wdyt?

Okay cool, let's go for that then! 👍

**Pull request closed without merging**
